### ISSUE TITLE
`google-api-client` should move from development dependency to dependency

### ISSUE THREAD

**Issue by ihmccreery** [fog/fog-google#11]
Right now, `google-api-client` is a development dependency, per fog/fog#1797; in the long-run it should be a runtime dependency.

We have to hold on this until `fog` no longer depends on `fog-google`, which will be a breaking change.  See fog's [Roadmap](https://github.com/fog/fog/wiki/Roadmap).

**Comment by ihmccreery** [comment]
Also remove extra `require` statement in `lib/fog/google.rb' and the "Please install the google-api-client gem before using this provider" warning.

**Comment by prees1** [comment]
I am not sure if this is related, if it is not I can post elsewhere to resolve. My issue is that I have installed the `google-api-client` gem but when I use fog with google as the provider I always get the "Please install the google-api-client gem before using this provider" warning and it does not work.

**Comment by Temikus** [comment]
@prees1 This is unrelated. Please, provide an example of what you're trying to do and file a new issue. I would suggest looking into the ruby load path to make sure you're loading the gem from the same version (`ruby -e 'puts $:'` from the same environment) and if you're using bundler, make sure it's actually bundled in properly with the correct version (< 0.9) as in: 
`gem 'google-api-client', '~> 0.8.6'`

**Comment by DawidJanczak** [comment]
Hi! Is this something that can get picked up soon? From what I see `fog` does not depend on `fog-google` anymore.

**Comment by Temikus** [comment]
@DawidJanczak It does: https://github.com/fog/fog/blob/master/fog.gemspec#L61

However, do note that since the metagem separation you should no longer need to use `fog` if you only need to work with Google. Requiring `fog-google` will suffice and bring the necessary core deps on its' own, hence the `Dependency notice` in README: https://github.com/fog/fog/blob/master/README.md#dependency-notice

**Comment by DawidJanczak** [comment]
Thank you @Temikus! So in case we only require `fog-google` and `google-api-client` (as recommended) it looks like `fog` gem as a whole won't get installed - only `fog-core` will.

The reason I'm asking is because I'm wondering whether this is still a blocker for https://github.com/fog/fog-google/pull/100, especially given that `fog-google` in `fog` gemspec is constrained to `<= 0.1.0`.

**Comment by Temikus** [comment]
@DawidJanczak 
On `fog` - that's WAI, `fog` is a legacy gem that exists there so we don't break peoples' existing setup and to access providers that haven't separated yet.

This issue doesn't have anything to do with #100 - `google-api-client` is a development dependency because we don't want to require it for other providers when used with `fog`, as the issue linked in this thread clearly says: https://github.com/fog/fog/pull/1797
