### ISSUE TITLE
Provisioning a server with the :preemptible option requires specifying :on_host_maintenance as well

### ISSUE THREAD

**Issue by selmanj** [fog/fog-google#136]
By default, the option for `:on_host_maintenance` is set to `MIGRATE`. However, if someone attempts to create a preemptible vm via `:preemptible`, then `:on_host_maintenance` must be set to `TERMINATE`. This is slightly surprising given that the google API documents the `onHostMaintanence` setting as:

> Defines the maintenance behavior for this instance. For standard instances, the default behavior is MIGRATE. For preemptible instances, the default and only possible behavior is TERMINATE.

https://cloud.google.com/compute/docs/reference/latest/instances#resource-representations

Given that this parameter is optional and by default set to the correct value, likely fog-google shouldn't specify it unless the request does.

**Comment by selmanj** [comment]
Alternatively, fog-google should use the same defaults.  I can understand doing this if the goal is to protect a default value changing in the api and then fog-google behaves differently, but specifying every parameter explicitly means that new feature additions that require different defaults will always require a code change

**Comment by Temikus** [comment]
@selmanj AFAIK the logic with preemptible was to not enforce defaults if the API changes or requires additional settings to be set for preemptible instances. Otherwise - we'll have people relying on parameters set by us and being unaware of the limitations of the additional options specified.

`MIGRATE` option being set by default, this seems to be stemming from a legacy commit made by @erjohnso:
https://github.com/fog/fog/pull/2811
Eric, maybe you have the context of why the scheduling was hardcoded?

If the raw API call succeeds without scheduling being set and we're not breaking anything else, I'm all for ripping this out in the next major version. We're tied to an API version in our requests anyway and, hopefully, GCE will not change how `insert` call behaves on a whim without incrementing the API version.

**Comment by erjohnso** [comment]
That was pre-preemptible. :)

Definitely not compatible with preemptible, so change away.
