### ISSUE TITLE
Per-instance sshKeys metadata is deprecated

### ISSUE THREAD

**Issue by wzzrd** [fog/fog-google#159]
When using fog-google (through Foreman), I see that it still uses the sshKeys metadata parameter. This call is deprecated and seems to result in project level SSH keys being blocked. See: https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys#deprecated

**Comment by icco** [comment]
@erjohnso are you guys deprecating things without bumping the api versions?

**Comment by Temikus** [comment]
@wzzrd Thank you for submitting this!

So, AFAIK the behavior of per-instance keys  was always like this, e.g. the VM will use only instance-level keys if present, project-level keys otherwise.

Do you have any evidence of the contrary? Did something break in your existing workflow?
If so - please, let me know, with an example, if possible.

I wasn't aware of it being marked as deprecated though, I'll look into it.

**Comment by Temikus** [comment]
@wzzrd + from the same doc you mentioned, there is a way to allow both per-instance and project wide keys by removing a parameter from metadata:
```
If an instance has the block-project-ssh-keys metadata value set to TRUE or has a deprecated instance-only sshKeys value, the instance ignores all project-wide SSH keys. To apply project-wide keys to that instance, remove the block-project-ssh-keys metadata value from that instance or remove the deprecated instance-only sshKeys value.
```

**Comment by Temikus** [comment]
They are indeed getting deprecated on March 17':

>Note: Setting the sshKeys metadata value on the instance metadata instead of the project metadata is deprecated. Compute Engine will stop supporting this metadata value in March 2017. Set the ssh-keys instance metadata value to add ssh keys for users on individual instances instead.
