### ISSUE TITLE
Implement CI for integration tests

### ISSUE THREAD

**Issue by Temikus** [fog/fog-google#192]
We need live feedback to contributors from integration tests. I've been thinking about this for a while, so I suppose a bug is in order to start. 

Since this is a possible security issue, I plan to implement it in the following way:

- [x] Get project and quota for it.
- [x] Set up metadata authentication for the instance in question.
- [x] Set up Concourse and a CI pipeline.
- [x] Set up a GitHub bot that will kick off builds after 👍  from one of the fog-google team members.
- [x] Make the build logs publicly accessible (probably spew out the build log to a bublic GS bucket)

@icco @selmanj WDYT?

**Comment by selmanj** [comment]
Sounds good to me. I've expressed in the past support for using VCR-style tests so that anyone can run the tests (which will greatly speed up local development before posting a PR), but I accept that the above is likely a prerequisite to this (once the above is up and running, it seems like the most natural place to double check that everything is still working).

The security issue does make me a bit worried though. Is there a good guide on how to do that in concourse? (ps: why concourse over jenkins or circle ci or any of the other solutions? I don't have a personal preference but am just curious)

**Comment by Temikus** [comment]
Note, the security concerns I'm talking about are rogue pull-requests, since the CI is authorized to spin up instances. That should be covered by the PR approval.

Honestly I want to try working with something new in CI space mostly, notably due to Jenkins:
- Being hard to set up from scratch and move around (a lot of disparate XML configs).
- Since it's a Tomcat app, it has a large attack surface with vulnerabilities posted often. 

Why concourse, is:
- Good API's
- Single binary with minimum dependencies, so should be easily portable
- I've heard many good things about it from good fellow engineers
- Built from the ground up around pipelines
- Low attack surface compared to Jenkins
- Actively developed

Mainly I want to set something up that can be easily redeployed and debuggable by other people.
Makes sense?

**Comment by Everlag** [comment]
@erjohnso Adding for context, though we also discussed over email.

**Comment by icco** [comment]
Ah, so only fog-google members will be able to see build runs, but everyone will be able to see logs? If so, this seems reasonable.

**Comment by Everlag** [comment]
It is configurable, everyone should be able to view success status of individual test steps while logs will be restricted to fog-google members.

**Comment by Temikus** [comment]
This is done \o/
