### ISSUE TITLE
ArgumentError: string contains null byte on file upload

### ISSUE THREAD

**Issue by kwatson** [fog/fog-google#298]
Hello,

I'm using carrierwave v1.2.2, and after upgrading fog-google from v0.6.0 to 1.1.0 (tried with anything over v1.0), i get the following error:

ArgumentError: string contains null byte
from ../google-api-client-0.19.1/lib/google/apis/core/upload.rb:56:in `initialize'

I've tried upgrading google-api-client to 0.19.4 and the issue still persists. Any ideas?

**Comment by icco** [comment]
hmm, I don't know enough about carrierwave, but my understanding of that error is it's because your file contains `\u0000`. If the same file worked before... that's slightly more concerning. 

It looks like carrierwave as a team hasn't tested the new fog-google version yet either, so there could be something wrong with their integration (which is at https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/storage/fog.rb#L316)

**Comment by kwatson** [comment]
Ok, thanks for that -- i'll open a ticket with carrierwave.

**Comment by kot-begemot** [comment]
Have you found solution to this problem?
