### ISSUE TITLE
GoogleXML::File should support private HTTPS url

### ISSUE THREAD

**Issue by micaelbergeron** [fog/fog-google#303]
# Problem
When using `GoogleXML::File.url`, the returned URL is always using the `http://` scheme. This will cause insecure redirects when trying to forward a request to the private URL of an object.

# Solution
The scheme should be configurable across all URL generation methods, so that you can serve HTTP/HTTPS urls from either private or public URLs.

See https://github.com/fog/fog-google/blob/30d6b447399146f1ed04daf35dd8d4bedffbd146/lib/fog/storage/google_xml/models/file.rb#L132

**Comment by icco** [comment]
We can totally change this. We like to keep the method signature close to fog-aws and googlejson.

AWS supports an optional option hash: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/storage/file.rb#L237

GoogleJson just dumps straight to https: https://github.com/fog/fog-google/blob/30d6b447399146f1ed04daf35dd8d4bedffbd146/lib/fog/storage/google_json/models/file.rb#L85

If you want to submit a PR that adds a json option hash to both, and makes https the default for XML, that'd be great. Otherwise I'll try to get to it soon.
