### ISSUE TITLE
GoogleJSON::Real#get_object returns Hash

### ISSUE THREAD

**Issue by Paxa** [fog/fog-google#312]
With recent update it started to return Hash instead of `Excon::Response`. Is it expected?

I started to get this errors:
```
undefined method `body' for #<Hash:0x0000555de8181708>
```

It comes from here:

https://github.com/fog/fog-google/blob/4422f4e1293c6b2a7668f1ca94185e36448290bd/lib/fog/storage/google_json/requests/get_object.rb#L56

I think `GoogleXML::Real#get_object` returns `Excon::Response` (according to code)

Current return value looks like this:
```ruby
{:bucket=>"bucket-name",
 :content_type=>"text/plain",
 :crc32c=>"M29jAg==",
 :etag=>"CMWhq8zc/9kCEAE=",
 :generation=>1521714589257925,
 :id=>"bucket-name/1/d0zmvii-47823baac19___/1521714589257___",
 :kind=>"storage#object",
 :md5_hash=>"hF2SCSSlV4gZPhJwoxmuPw==",
 :media_link=>
  "https://www.googleapis.com/download/storage/v1/b/bucket-name/o/1%2Fd0zmvii-47823baac19c35?generation=1521714589257925&alt=media",
 :metageneration=>1,
 :name=>"1/d0zmvii-47823baac19c35",
 :self_link=>
  "https://www.googleapis.com/storage/v1/b/bucket-name/o/1%2Fd0zmvii-47823baac19c35",
 :size=>15616,
 :storage_class=>"REGIONAL",
 :time_created=>Thu, 22 Mar 2018 10:29:49 +0000,
 :time_storage_class_updated=>Thu, 22 Mar 2018 10:29:49 +0000,
 :updated=>Thu, 22 Mar 2018 10:29:49 +0000,
 :body=> "content here"
}
```

**Comment by icco** [comment]
Yeah, this is intentional. It's mainly because we aren't using Excon in GoogleJSON. So all responses are coming from google-api-client which returns a hash ~always.

GoogleXML is essentially a fork of fog-aws's earlier s3 implementation (because GoogleXML used to be api identical to S3), and so uses Excon, which specializes in XML and http requests, and also google-api-client does not support non-json APIs, even though they are published by google.
