### ISSUE TITLE
Meta tests in `fog-google`

### ISSUE THREAD

**Issue by ihmccreery** [fog/fog-google#4]
@plribeiro3000 Thanks again for doing the extraction.

I'm getting ready to cut a gem for `fog-google`, but I wanted to make sure all of the tests are passing properly and that we're not missing any components.

When I run the tests inside `fog-google` versus `fog`, (using `sh("export FOG_MOCK=#{mock} && bundle exec shindont tests/google")`), pretty much everything looks the same, except that the `fog-google` test suite seems to have following two lines that the `fog` tests don't, with 48 tests missing:

```
Fog::Schema::DataValidator (meta) +++++++++++++++++++++++
test_helper (meta) +++++++++++++++++++++++++
```

Should these tests be here?  Seems weird to me that they are.  It may very well be an artifact of other weird things that are going on.

**Comment by plribeiro3000** [comment]
It is because of the way `shindo` works i guess. 
It has some helpers inside [`helpers`](https://github.com/fog/fog/tree/master/tests/helpers) to be used within the tests but as we can see i think they run as standalone as well.

The reason you can't see them running the above command in `fog` is because you are explicity telling it to run just the tests inside the `google` folder and thus ignore the helper ones.

**Comment by plribeiro3000** [comment]
@ihmccreery Is this ok. Can this issue be closed?

**Comment by ihmccreery** [comment]
If it's okay, I'd like to keep this open, and close it once we have the tests moved over to `minitest`.

**Comment by plribeiro3000** [comment]
@ihmccreery Sure, you are the boss here. i was asking btw, just forgot to add the `?` mark. hahahah

**Comment by Temikus** [comment]
Closing in favor of #50
