### ISSUE TITLE
Update dependency to google-api-ruby >= 0.27.3 to support custom hostname

### ISSUE THREAD

**Issue by eLvErDe** [fog/fog-google#479]
Hello,

Could you please consider making 0.27.3 the minimum required version ? It's the first version supporting "hostname" parameter to set a custom hostname and I think it's an important feature.

https://github.com/googleapis/google-api-ruby-client/blob/0.27.3/generated/google/apis/compute_v1/classes.rb#L7159

Also releasing a GEM would be great, so Foreman can update its dependencies and provide "hostname" integration as well.

Thanks  in advance,

Adam.

**Comment by Temikus** [comment]
@eLvErDe Just updated the gemspec since we needed to bump for Stackdriver anyway: https://github.com/fog/fog-google/blob/master/fog-google.gemspec#L29

I am planning to roll up a release soon-ish (within the next month). I have been away for a while due to medical reasons so it'll take me a bit to fixup everything.

I'll resolve this but feel free to reopen if I missed anything.

**Comment by eLvErDe** [comment]
Great thanks a lot.
Hope you'll recover just fine!
